エラーの修正 エラーの暫定的な修正を行いました。
Error in on_ready
TypeError: TC_to_EC.__init__() missing 1 required positional argument: 'bot'